name: Run Postman Collection with HTML Report and Coverage Check

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  postman_tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (Newman and HTML Reporter)
      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      # Step 4: Run the Postman collection and generate both JSON and HTML reports
      - name: Run Postman Collection and Generate Reports
        run: |
          npx newman run postman/sys-api-oauth.postman_collection.json \
          --environment postman/sys-api-oauth.postman_environment.json \
          --reporters cli,json,html \
          --reporter-json-export newman/newman-report.json \
          --reporter-html-export newman/newman-report.html

      # Step 5: Output JSON report content (Debugging)
      - name: Output newman-report.json for Debugging
        run: |
          echo "Newman JSON Report Contents:"
          cat newman/newman-report.json

      # Step 6: Calculate Test Coverage Based on Newman JSON Report
      - name: Calculate Test Coverage
        id: coverage
        run: |
          # Parse the Newman JSON report and calculate test coverage
          TOTAL_TESTS=$(jq '.run.stats.tests.total' newman/newman-report.json)
          PASSED_TESTS=$(jq '.run.stats.tests.passed' newman/newman-report.json)

          if [ "$TOTAL_TESTS" == "null" ] || [ "$PASSED_TESTS" == "null" ]; then
            echo "Error: Failed to extract test stats from the Newman report."
            exit 1
          fi

          # Calculate coverage percentage
          COVERAGE=$(echo "scale=2; ($PASSED_TESTS / $TOTAL_TESTS) * 100" | bc)

          echo "Total Tests: $TOTAL_TESTS"
          echo "Passed Tests: $PASSED_TESTS"
          echo "Coverage: $COVERAGE%"

          # Fail the workflow if coverage is less than 80%
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80% ($COVERAGE%)"
            exit 1
          else
            echo "Test coverage is above 80% ($COVERAGE%)"
          fi

      # Step 7: Upload HTML Report as an Artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman/newman-report.html

      # Step 8: Deploy Only if Coverage is Greater Than 80%
      - name: Deploy Application
        if: success()
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
